# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# clip.py
# Created on: 2023-09-20 07:28:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
MUNICIPIO_shp = "\\\\Mac\\Home\\Desktop\\catastro rosarito\\database\\PREDIOS ROSARITO\\BASE\\MUNICIPIO.shp"
terreno_shp = "\\\\Mac\\Home\\Desktop\\catastro rosarito\\database\\PREDIOS ROSARITO\\terreno.shp"
Recorte_shp = "\\\\Mac\\Home\\Desktop\\catastro rosarito\\database\\PREDIOS ROSARITO\\Recorte_python.shp"

# Process: Clip
arcpy.Clip_analysis(MUNICIPIO_shp, terreno_shp, Recorte_shp, "")

